version: '3'
services:
  bot:
    build: .
    environment:
      - MONGO_CONNECTION=mongodb://${DB_USERNAME}:${DB_PASSWORD}@${DATABASE_HOST}/${DB_DATABASE}
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./avatars:/app/avatars
  db:
    image: mongo
    volumes:
      - ./data:/data/db
      - ./mongo_entrypoint:/docker-entrypoint-initdb.d
    env_file:
      - .env
    ports:
      - "27017:27017"
  miniapp_api:
    build:
      context: .
      dockerfile: ./src/miniapp_api/Dockerfile
    environment:
      - MONGO_CONNECTION=mongodb://${DB_USERNAME}:${DB_PASSWORD}@${DATABASE_HOST}/${DB_DATABASE}
    env_file:
      - .env
    container_name: miniapp_api
    ports:
      - "4242:4242"
    depends_on:
      - db
    volumes:
      - ./avatars:/app/avatars
      - ./sessions:/app/sessions
  userbot_polling:
    build:
      context: .
      dockerfile: ./src/analytics/Dockerfile
    env_file:
      - .env
    environment:
      - MONGO_CONNECTION=mongodb://${DB_USERNAME}:${DB_PASSWORD}@${DATABASE_HOST}/${DB_DATABASE}
    container_name: userbot_polling
    volumes:
      - ./sessions:/app/sessions
      - ./data:/data/db
